### ISSUE TITLE
Project is now deprecated

### ISSUE THREAD

**Issue by McPo** [bytheway/electron-sqlite3#4]
Hi.

This project is now redundant as sqlite3@3.1.3 supports electron and sqlite3@3.1.4 now supports Node v6.x.

I initially thought there was an issue with the latest sqlite3, turns out I was attempting to access it from the rendering process which spitted out all sorts of errors, including missing files and modules. So make sure your accessing the DB from the main process not the render process.

https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md

Could you add deprecated notice to the readme.

**Comment by bytheway** [comment]
Thanks, I'll check out how the integration works with the newer versions and decide how to move forward with this example project.

**Comment by McPo** [comment]
Apologies.
This project is still very much needed. I was running the DB code within the dev server.

Im currently working on getting sqlcipher up and going. At which point Ill make a PR for the latest version of electron along with optional sqlcipher support.
